apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-db5039edf02843249534f9526ea9a6a3-depl
  labels:
    app: coll-db5039edf02843249534f9526ea9a6a3
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-db5039edf02843249534f9526ea9a6a3
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-db5039edf02843249534f9526ea9a6a3
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-db5039edf02843249534f9526ea9a6a3
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-db5039edf02843249534f9526ea9a6a3
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping